# Change these first
owner: nileshsalunke09 # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Linux-Shell-Scripting
    url: https://nileshsalunke09.github.io/Linux-Shell-Scripting/
  - name: OpenSpecimen_Demo-Site
    url: https://demo.openspecimen.org/
  - name: OpenSpecimen_Test-Site
    url: https://test.openspecimen.org/
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime by Nilesh
  introTitle: "**Upptime**."
  introMessage: Below is the Test, Demo website status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      



# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
